image: debian:stretch
stages:
  - build
before_script:
  - apt-get update -qq
  - apt-get upgrade -qq
  - apt-get --assume-yes -qq install libboost-all-dev cmake devscripts debhelper libseccomp-dev pkg-config
build:
  stage: build
  script:
    - dpkg-buildpackage -uc -us
    - mkdir build
    - mv ../tcpdup_*.deb .
  artifacts:
    paths:
    - tcpdup_*.deb
